/**
 * Converts the Expo client's i18n dictionaries into Dart.
 *
 * `src/i18n/zh.ts` is the source of truth for the key set, and `en.ts` is typechecked
 * against it upstream. Reading them here rather than retyping 419 strings means the two
 * clients cannot drift: the Chinese copy stays byte-identical, which is what the
 * translation review upstream was done against.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const SRC = fileURLToPath(new URL("../../mobile/src/i18n/", import.meta.url));

function parseDictionary(file) {
  const text = readFileSync(`${SRC}/${file}`, "utf8");
  const entries = [];
  // `"key": "value",` — values may contain escapes and `{placeholders}`.
  const pattern = /^\s*"([^"]+)":\s*"((?:[^"\\]|\\.)*)",\s*$/gm;
  let match;
  while ((match = pattern.exec(text)) !== null) entries.push([match[1], match[2]]);
  return entries;
}

/** Dart string literal: escape what Dart treats specially, keep `{name}` intact. */
function dartString(value) {
  return `'${value
    .replace(/\\"/g, '"')
    .replace(/\\n/g, "\\n")
    .replace(/'/g, "\\'")
    .replace(/\$/g, "\\$")}'`;
}

function render(name, entries, doc) {
  const lines = entries.map(([key, value]) => `  ${dartString(key)}: ${dartString(value)},`);
  return `${doc}
const Map<String, String> ${name} = <String, String>{
${lines.join("\n")}
};
`;
}

const zh = parseDictionary("zh.ts");
const en = parseDictionary("en.ts");
const zhKeys = new Set(zh.map(([key]) => key));

// `_one` entries exist only in English (the plural rule is `count == 1`), so they are
// kept but verified to belong to a key the source dictionary has.
const orphans = en.filter(([key]) => !zhKeys.has(key) && !zhKeys.has(key.replace(/_one$/, "")));
if (orphans.length) {
  console.error("English keys with no Chinese source:", orphans.map(([key]) => key));
  process.exit(1);
}
const missing = [...zhKeys].filter((key) => !en.some(([candidate]) => candidate === key));
if (missing.length) {
  console.error("Chinese keys with no English translation:", missing);
  process.exit(1);
}

const banner = `// GENERATED by tool/gen_i18n.mjs from apps/mobile/src/i18n — do not edit by hand.
// The key set and the Chinese copy come from the Expo client so the two cannot drift.
`;

writeFileSync(
  new URL("../lib/i18n/zh.dart", import.meta.url),
  render("zh", zh, banner),
);
writeFileSync(
  new URL("../lib/i18n/en.dart", import.meta.url),
  render("en", en, banner),
);
console.log(`zh: ${zh.length} keys, en: ${en.length} entries`);
