/**
 * Generates Dart dictionaries from this client's tool/i18n/{zh,en}.json.
 * Chinese defines the key set; English can add `_one` singular forms.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const SRC = fileURLToPath(new URL("./i18n/", import.meta.url));

function parseDictionary(file) {
  const dictionary = JSON.parse(readFileSync(`${SRC}/${file}`, "utf8"));
  if (!dictionary || Array.isArray(dictionary) || typeof dictionary !== "object") {
    throw new Error(`${file} must be an object of translation strings`);
  }
  const entries = Object.entries(dictionary);
  if (!entries.length || entries.some(([, value]) => typeof value !== "string")) {
    throw new Error(`${file} must contain nonempty translation entries with string values`);
  }
  return entries;
}

/** Dart string literal: escape what Dart treats specially, keep `{name}` intact. */
function dartString(value) {
  return `'${value
    .replace(/\\/g, "\\\\")
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t")
    .replace(/'/g, "\\'")
    .replace(/\$/g, "\\$")}'`;
}

function render(name, entries, doc) {
  const lines = entries.map(([key, value]) => `  ${dartString(key)}: ${dartString(value)},`);
  return `${doc}
const Map<String, String> ${name} = <String, String>{
${lines.join("\n")}
};
`;
}

const zh = parseDictionary("zh.json");
const en = parseDictionary("en.json");
const zhKeys = new Set(zh.map(([key]) => key));

// `_one` entries exist only in English (the plural rule is `count == 1`), so they are
// kept but verified to belong to a key the source dictionary has.
const orphans = en.filter(([key]) => !zhKeys.has(key) && !zhKeys.has(key.replace(/_one$/, "")));
if (orphans.length) {
  console.error("English keys with no Chinese source:", orphans.map(([key]) => key));
  process.exit(1);
}
const missing = [...zhKeys].filter((key) => !en.some(([candidate]) => candidate === key));
if (missing.length) {
  console.error("Chinese keys with no English translation:", missing);
  process.exit(1);
}

const banner = `// GENERATED by tool/gen_i18n.mjs from tool/i18n/{zh,en}.json — do not edit by hand.
`;

for (const [name, entries] of [["zh", zh], ["en", en]]) {
  const output = new URL(`../lib/i18n/${name}.dart`, import.meta.url);
  const generated = render(name, entries, banner);
  if (process.argv.includes("--check")) {
    if (readFileSync(output, "utf8") !== generated) {
      throw new Error(`${name}.dart is stale; run pnpm flutter:i18n`);
    }
  } else {
    writeFileSync(output, generated);
  }
}
console.log(`zh: ${zh.length} keys, en: ${en.length} entries`);
