import type { IconSvgElement } from "@hugeicons/react-native";

/**
 * Every icon the app draws, each from its own module.
 *
 * Never import from `@hugeicons/core-free-icons` itself: Metro does not tree-shake, so
 * the package index pulls in all ~6000 icons — 7.7 MB of source, over half of the JS
 * bundle, for the few dozen used here. The per-icon files ship without type
 * declarations, which `hugeicons.d.ts` supplies.
 */
import AiBrain01IconSvg from "@hugeicons/core-free-icons/AiBrain01Icon";
import Alert02IconSvg from "@hugeicons/core-free-icons/Alert02Icon";
import Archive02IconSvg from "@hugeicons/core-free-icons/Archive02Icon";
import ArchiveArrowUpIconSvg from "@hugeicons/core-free-icons/ArchiveArrowUpIcon";
import ArrowDown01IconSvg from "@hugeicons/core-free-icons/ArrowDown01Icon";
import ArrowDown02IconSvg from "@hugeicons/core-free-icons/ArrowDown02Icon";
import ArrowRight01IconSvg from "@hugeicons/core-free-icons/ArrowRight01Icon";
import ArrowUp02IconSvg from "@hugeicons/core-free-icons/ArrowUp02Icon";
import BotIconSvg from "@hugeicons/core-free-icons/BotIcon";
import BubbleChatIconSvg from "@hugeicons/core-free-icons/BubbleChatIcon";
import Bug01IconSvg from "@hugeicons/core-free-icons/Bug01Icon";
import Cancel01IconSvg from "@hugeicons/core-free-icons/Cancel01Icon";
import ChatAdd01IconSvg from "@hugeicons/core-free-icons/ChatAdd01Icon";
import CheckmarkCircle02IconSvg from "@hugeicons/core-free-icons/CheckmarkCircle02Icon";
import ChromeIconSvg from "@hugeicons/core-free-icons/ChromeIcon";
import Clock01IconSvg from "@hugeicons/core-free-icons/Clock01Icon";
import CodeIconSvg from "@hugeicons/core-free-icons/CodeIcon";
import ComputerIconSvg from "@hugeicons/core-free-icons/ComputerIcon";
import Copy01IconSvg from "@hugeicons/core-free-icons/Copy01Icon";
import Delete02IconSvg from "@hugeicons/core-free-icons/Delete02Icon";
import FileEditIconSvg from "@hugeicons/core-free-icons/FileEditIcon";
import FileMinusIconSvg from "@hugeicons/core-free-icons/FileMinusIcon";
import FilePlusIconSvg from "@hugeicons/core-free-icons/FilePlusIcon";
import FileTextIconSvg from "@hugeicons/core-free-icons/FileTextIcon";
import Folder01IconSvg from "@hugeicons/core-free-icons/Folder01Icon";
import FolderTreeIconSvg from "@hugeicons/core-free-icons/FolderTreeIcon";
import Globe02IconSvg from "@hugeicons/core-free-icons/Globe02Icon";
import HandIconSvg from "@hugeicons/core-free-icons/HandIcon";
import Idea01IconSvg from "@hugeicons/core-free-icons/Idea01Icon";
import InformationCircleIconSvg from "@hugeicons/core-free-icons/InformationCircleIcon";
import Link01IconSvg from "@hugeicons/core-free-icons/Link01Icon";
import ListChecksIconSvg from "@hugeicons/core-free-icons/ListChecksIcon";
import Loading03IconSvg from "@hugeicons/core-free-icons/Loading03Icon";
import LockPasswordIconSvg from "@hugeicons/core-free-icons/LockPasswordIcon";
import MessageQuestionIconSvg from "@hugeicons/core-free-icons/MessageQuestionIcon";
import MoreHorizontalIconSvg from "@hugeicons/core-free-icons/MoreHorizontalIcon";
import PencilEdit02IconSvg from "@hugeicons/core-free-icons/PencilEdit02Icon";
import PlayIconSvg from "@hugeicons/core-free-icons/PlayIcon";
import Plug01IconSvg from "@hugeicons/core-free-icons/Plug01Icon";
import QrCode01IconSvg from "@hugeicons/core-free-icons/QrCode01Icon";
import Refresh01IconSvg from "@hugeicons/core-free-icons/Refresh01Icon";
import ScissorIconSvg from "@hugeicons/core-free-icons/ScissorIcon";
import Search01IconSvg from "@hugeicons/core-free-icons/Search01Icon";
import Settings02IconSvg from "@hugeicons/core-free-icons/Settings02Icon";
import ShieldAlertIconSvg from "@hugeicons/core-free-icons/ShieldAlertIcon";
import ShieldCheckIconSvg from "@hugeicons/core-free-icons/ShieldCheckIcon";
import SparklesIconSvg from "@hugeicons/core-free-icons/SparklesIcon";
import SquareIconSvg from "@hugeicons/core-free-icons/SquareIcon";
import SquareTerminalIconSvg from "@hugeicons/core-free-icons/SquareTerminalIcon";
import Sun03IconSvg from "@hugeicons/core-free-icons/Sun03Icon";
import TestTube01IconSvg from "@hugeicons/core-free-icons/TestTube01Icon";
import Tick02IconSvg from "@hugeicons/core-free-icons/Tick02Icon";
import TouchInteraction01IconSvg from "@hugeicons/core-free-icons/TouchInteraction01Icon";
import WifiDisconnected02IconSvg from "@hugeicons/core-free-icons/WifiDisconnected02Icon";
import Wrench01IconSvg from "@hugeicons/core-free-icons/Wrench01Icon";

export const AiBrain01Icon: IconSvgElement = AiBrain01IconSvg;
export const Alert02Icon: IconSvgElement = Alert02IconSvg;
export const Archive02Icon: IconSvgElement = Archive02IconSvg;
export const ArchiveArrowUpIcon: IconSvgElement = ArchiveArrowUpIconSvg;
export const ArrowDown01Icon: IconSvgElement = ArrowDown01IconSvg;
export const ArrowDown02Icon: IconSvgElement = ArrowDown02IconSvg;
export const ArrowRight01Icon: IconSvgElement = ArrowRight01IconSvg;
export const ArrowUp02Icon: IconSvgElement = ArrowUp02IconSvg;
export const BotIcon: IconSvgElement = BotIconSvg;
export const BubbleChatIcon: IconSvgElement = BubbleChatIconSvg;
export const Bug01Icon: IconSvgElement = Bug01IconSvg;
export const Cancel01Icon: IconSvgElement = Cancel01IconSvg;
export const ChatAdd01Icon: IconSvgElement = ChatAdd01IconSvg;
export const CheckmarkCircle02Icon: IconSvgElement = CheckmarkCircle02IconSvg;
export const ChromeIcon: IconSvgElement = ChromeIconSvg;
export const Clock01Icon: IconSvgElement = Clock01IconSvg;
export const CodeIcon: IconSvgElement = CodeIconSvg;
export const ComputerIcon: IconSvgElement = ComputerIconSvg;
export const Copy01Icon: IconSvgElement = Copy01IconSvg;
export const Delete02Icon: IconSvgElement = Delete02IconSvg;
export const FileEditIcon: IconSvgElement = FileEditIconSvg;
export const FileMinusIcon: IconSvgElement = FileMinusIconSvg;
export const FilePlusIcon: IconSvgElement = FilePlusIconSvg;
export const FileTextIcon: IconSvgElement = FileTextIconSvg;
export const Folder01Icon: IconSvgElement = Folder01IconSvg;
export const FolderTreeIcon: IconSvgElement = FolderTreeIconSvg;
export const Globe02Icon: IconSvgElement = Globe02IconSvg;
export const HandIcon: IconSvgElement = HandIconSvg;
export const Idea01Icon: IconSvgElement = Idea01IconSvg;
export const InformationCircleIcon: IconSvgElement = InformationCircleIconSvg;
export const Link01Icon: IconSvgElement = Link01IconSvg;
export const ListChecksIcon: IconSvgElement = ListChecksIconSvg;
export const Loading03Icon: IconSvgElement = Loading03IconSvg;
export const LockPasswordIcon: IconSvgElement = LockPasswordIconSvg;
export const MessageQuestionIcon: IconSvgElement = MessageQuestionIconSvg;
export const MoreHorizontalIcon: IconSvgElement = MoreHorizontalIconSvg;
export const PencilEdit02Icon: IconSvgElement = PencilEdit02IconSvg;
export const PlayIcon: IconSvgElement = PlayIconSvg;
export const Plug01Icon: IconSvgElement = Plug01IconSvg;
export const QrCode01Icon: IconSvgElement = QrCode01IconSvg;
export const Refresh01Icon: IconSvgElement = Refresh01IconSvg;
export const ScissorIcon: IconSvgElement = ScissorIconSvg;
export const Search01Icon: IconSvgElement = Search01IconSvg;
export const Settings02Icon: IconSvgElement = Settings02IconSvg;
export const ShieldAlertIcon: IconSvgElement = ShieldAlertIconSvg;
export const ShieldCheckIcon: IconSvgElement = ShieldCheckIconSvg;
export const SparklesIcon: IconSvgElement = SparklesIconSvg;
export const SquareIcon: IconSvgElement = SquareIconSvg;
export const SquareTerminalIcon: IconSvgElement = SquareTerminalIconSvg;
export const Sun03Icon: IconSvgElement = Sun03IconSvg;
export const TestTube01Icon: IconSvgElement = TestTube01IconSvg;
export const Tick02Icon: IconSvgElement = Tick02IconSvg;
export const TouchInteraction01Icon: IconSvgElement = TouchInteraction01IconSvg;
export const WifiDisconnected02Icon: IconSvgElement = WifiDisconnected02IconSvg;
export const Wrench01Icon: IconSvgElement = Wrench01IconSvg;
